"""empty message

迁移 ID: 33655e2b5d91
父迁移: fd4af3c9abc4
创建时间: 2026-02-22 21:53:46.809162

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '33655e2b5d91'
down_revision: str | Sequence[str] | None = 'fd4af3c9abc4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_groupblacklist',
    sa.Column('group_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_blacklist_groupblacklist')),
    sa.UniqueConstraint('group_id', name='group_blacklist_uc'),
    info={'bind_key': 'blacklist'}
    )
    op.create_table('blacklist_userblacklist',
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_blacklist_userblacklist')),
    sa.UniqueConstraint('user_id', name='user_blacklist_uc'),
    info={'bind_key': 'blacklist'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_userblacklist')
    op.drop_table('blacklist_groupblacklist')
    # ### end Alembic commands ###
