"""empty message

迁移 ID: fd1877d177ff
父迁移: 
创建时间: 2026-02-22 23:07:55.785258

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fd1877d177ff'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_groupblacklist',
    sa.Column('group_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_blacklist_groupblacklist')),
    sa.UniqueConstraint('group_id', name='group_blacklist_uc'),
    info={'bind_key': 'blacklist'}
    )
    op.create_table('blacklist_userblacklist',
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_blacklist_userblacklist')),
    sa.UniqueConstraint('user_id', name='user_blacklist_uc'),
    info={'bind_key': 'blacklist'}
    )
    op.create_table('database_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_database_groups')),
    info={'bind_key': 'database'}
    )
    op.create_table('database_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_database_users')),
    info={'bind_key': 'database'}
    )
    op.create_table('birthday_groupsettings',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.Column('last_reply_ts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['database_groups.id'], name=op.f('fk_birthday_groupsettings_group_id_database_groups')),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_birthday_groupsettings')),
    info={'bind_key': 'birthday'}
    )
    op.create_table('birthday_userbirthday',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('birthday_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['database_users.id'], name=op.f('fk_birthday_userbirthday_user_id_database_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_birthday_userbirthday')),
    info={'bind_key': 'birthday'}
    )
    op.create_table('birthday_usergroupusage',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['database_groups.id'], name=op.f('fk_birthday_usergroupusage_group_id_database_groups')),
    sa.ForeignKeyConstraint(['user_id'], ['database_users.id'], name=op.f('fk_birthday_usergroupusage_user_id_database_users')),
    sa.PrimaryKeyConstraint('user_id', 'group_id', 'day', name=op.f('pk_birthday_usergroupusage')),
    info={'bind_key': 'birthday'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birthday_usergroupusage')
    op.drop_table('birthday_userbirthday')
    op.drop_table('birthday_groupsettings')
    op.drop_table('database_users')
    op.drop_table('database_groups')
    op.drop_table('blacklist_userblacklist')
    op.drop_table('blacklist_groupblacklist')
    # ### end Alembic commands ###
