"""empty message

迁移 ID: fd4af3c9abc4
父迁移: 7f46d7ed146b
创建时间: 2026-02-22 20:00:35.622198

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fd4af3c9abc4'
down_revision: str | Sequence[str] | None = '7f46d7ed146b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birthday_groupsettings',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.Column('last_reply_ts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['database_groups.id'], name=op.f('fk_birthday_groupsettings_group_id_database_groups')),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_birthday_groupsettings')),
    info={'bind_key': 'birthday'}
    )
    op.create_table('birthday_userbirthday',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('birthday_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['database_users.id'], name=op.f('fk_birthday_userbirthday_user_id_database_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_birthday_userbirthday')),
    info={'bind_key': 'birthday'}
    )
    op.create_table('birthday_usergroupusage',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['database_groups.id'], name=op.f('fk_birthday_usergroupusage_group_id_database_groups')),
    sa.ForeignKeyConstraint(['user_id'], ['database_users.id'], name=op.f('fk_birthday_usergroupusage_user_id_database_users')),
    sa.PrimaryKeyConstraint('user_id', 'group_id', 'day', name=op.f('pk_birthday_usergroupusage')),
    info={'bind_key': 'birthday'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birthday_usergroupusage')
    op.drop_table('birthday_userbirthday')
    op.drop_table('birthday_groupsettings')
    # ### end Alembic commands ###
